# Match resolver with nixos-unstable haskellPackages
resolver: lts-20.15
packages:
- cachix
- cachix-api
extra-deps:
- nix-narinfo-0.1.0.1
- fsnotify-0.4.1.0
- hnix-store-core-0.6.1.0
- saltine-0.2.0.1
nix:
  enable: true
  pure: false
  shell-file: ./shell.nix
