name: "Latest tag"
on:
  push:
    branches:
      - master
jobs:
  latest-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update 'latest' git tag
      uses: EndBug/latest-tag@latest
