name: "Release"
on:
  push:
    tags:
      - v**
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/haskell-release-action@v1
      with:
        branch: master
        work-dir: cachix-api
        hackage-token: ${{ secrets.HACKAGE_AUTH_TOKEN }}
    - uses: cachix/haskell-release-action@v1
      with:
        branch: master
        work-dir: cachix
        hackage-token: ${{ secrets.HACKAGE_AUTH_TOKEN }}
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: cachix
    - run: nix build -L '.#ci' '.#cachix' --show-trace --impure
  pin:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: cachix
    - run: cachix pin cachix ${{ github.ref_name }} $(nix build '.#cachix' --impure --print-out-paths)


