name: Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - uses: cachix/cachix-action@v13
      with:
        name: cachix

    - uses: sol/haskell-autotag@v1
      id: autotag
    
    - run: cabal sdist
    - run: cd cachix-api && cabal sdist

    - uses: haskell-actions/hackage-publish@v1
      with:
        # http://hackage.haskell.org/users/account-management
        hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
        publish: true
      if: steps.autotag.outputs.created

    - run: cachix pin cachix ${{ github.ref_name }} $(nix build '.#cachix' --impure --print-out-paths)
      if: steps.autotag.outputs.created
